# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 866dfc79ed2003a008b1e32bc23acbf585094c5da42e04eb39710af81d5591503cd5017f8a89b2d7dda2be5a730b8f80c19436b308d36383f5dafaf10b7ad116

test:
  secret_key_base: 4bcb14ce4b80b5d2320f6858e555e9e2ff336763f17b400c932b5d71a13ca33dd73ee18e4aef84d78f014e73acb402ebfe4533b6b8b58a85ca26ab21cf59466a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
